language: cpp
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
python: "3.8"
addons:
  apt:
    packages:
      - gfortran
      - libgsl0-dev
      - libsqlite3-dev
  homebrew:
    packages:
      - gcc
      - gsl
      - sqlite
    update: true
install:
  - export PATH=$(python -c 'import site; print(site.USER_BASE + "/bin")'):$PATH
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$CXX" == "g++" ]]; then export CXX="g++-9" CC="gcc-9"; fi
  - pip install --user conan
  - conan remote add conan-hep https://api.bintray.com/conan/expander/conan-hep --force
  - conan install . --build=missing
script:
  - >
    ./configure
    --with-cxxflags="-std=c++14 -fPIC"
    --with-optional-modules=test
    --with-addons=GM2Calc
    --with-loop-libraries=collier,looptools
    --with-install-dir=install
    --disable-meta
  - make showbuild
  - make -j2
  - make -j2 -k all-test
  - make install-src
before_cache:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cleanup ; fi
cache:
  pip: true
  directories:
    - $HOME/.conan
    - $HOME/Library/Caches/Homebrew
    - /usr/local/Homebrew
